### PR TITLE
fixed pixelated font 

### LINKED ISSUE #3: Fonts on Chrome 67 on MacOS 10.2.6 appear pixelated and uneven.
screen shot 2018-06-05 at 2 12 47 pm

### PR DESCRIPTION
**Pull request by AmirBraham**
fixed pixelated font . #3

from : 
screen shot 2018-06-05 at 10 43 12 pm

to : 
screen shot 2018-06-05 at 10 42 33 pm

### CODE REVIEW

**Comment by kessiler** [comment]
Turn on ClearType 🌝

**Comment by martenbjork** [comment]
Thanks for the feedback regarding this (and for the PR)! The poor rendering is actually intentional and part of the joke. 🙃

**Comment by kessiler** [comment]
@martenbjork you may want to add this - https://www.windowscentral.com/how-make-text-easier-read-using-cleartype-windows-10

**Comment by onewheelskyward** [comment]
Oh for the love of...that's hilarious.  Well played @martenbjork .  :)

**Comment by roNn23** [comment]
Well, I can see the joke, but on mac, it's not useable at all without font-smoothing... :/ 
bildschirmfoto 2018-06-06 um 08 38 13

**Pull request closed without merging**
