### PR TITLE
Fixes logo position in firefox

### PR DESCRIPTION
**Pull request by Frederick888**
Tested in Chrome as well and found no side effects.

How it looks like without the fix in Firefox FYI: screenshot_20180607_190642

### CODE REVIEW

**Comment by Frederick888** [comment]
Mmmmm... wait a second... Sometimes I have to refresh for the fix to take effect. I guess it's related to when Stylish loads the CSS and how `unset` is handled by Firefox...

**Comment by martenbjork** [comment]
Hi @Frederick888, would you like this merged? Saw some flickering issues too.

**Comment by Frederick888** [comment]
@martenbjork Well, I changed it to `initial` and and it still has the same problem.
If you're ok with it then I reckon we could merge it for now and see whether we can come up with something better down the line.

**Comment by martenbjork** [comment]
OK, merged! Thanks for helping out :)

**Pull request merged**
